[package]
name = "libtapasco_tests"
version = "1.0.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
tapasco = { path = "../../../libtapasco" }
env_logger = "0.9.0"
clap = "3.1.6"
log = "0.4.14"
snafu = "0.7.0"
indicatif = "0.16.2"
average = "0.13.1"
uom = "0.32.0"
rayon = "1.5.1"
num_cpus = "1.13.0"
crossbeam = "0.8.1"
rand = "0.8.4"
itertools = "0.10.1"
